- meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/entity/MedicalRecord.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/vo/GetMedicalRecordsVo.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordResponseDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponseDto.java
- meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
> feat: 진료 기록 API

- meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
- meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightRepository.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/vo/GetMonthWeightVO.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/vo/GetWeekWeightVO.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeightMonthResponse.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeightWeekResponse.java
- meongcare/src/main/java/com/meongcare/infra/config/S3Config.java
주별 조회 시에 week() 함수를 쓰면 주차 매핑이 제대로 안되어서
1~4주차동안 LocalDateTime을 다 조회해서 코드레벨에서 매핑하는 걸로 구현했습니다.
> feat: 몸무게 주별, 월별 조회 및 몸무게 업데이트 API

- meongcare/build.gradle
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponseDto.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/ReissueResponseDto.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
- meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/response/GetExcretaResponse.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequestDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordResponseDto.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponseDto.java
- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/SymptomController.java
- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/EditSymptomRequest.java
- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/SaveSymptomRequest.java
- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/response/GetSymptomResponse.java
- meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetMonthWeightResponse.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeekWeightResponse.java
- meongcare/src/main/java/com/meongcare/infra/image/s3/S3Api.java
일단 제가 아는것까진 설정을 했습니다.
동천님이 개발하신 남은 컨트롤러, DTO 해주시면 감사하겠습니다..~~
> docs: Swagger(openapi) 설정

- meongcare/build.gradle
- meongcare/src/main/java/com/meongcare/common/BaseEntity.java
- meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
- meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightJdbcRepository.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/vo/GetLastDayWeightVO.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/request/SaveWeightRequest.java
로직에 허점이 있다면 적극적으로 의견을 남겨주세요.
아무튼 기나긴 몸무게 INSERT API 구현을 완료했습니다..
> feat: 몸무게 조회, 나의 정보에서 몸무게 수정 시 몸무게 INSERT API

- meongcare/src/main/java/com/meongcare/common/BaseEntity.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightJdbcRepository.java
> refactor: 디폴트 값 지정을 통해 생성일자 입력

- meongcare/.gitignore
- meongcare/build.gradle
- meongcare/src/main/java/com/meongcare/MeongcareApplication.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtValidation.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/SymptomController.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
- meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
- meongcare/src/main/java/com/meongcare/infra/config/WebConfig.java
- CORS 허용 설정, JWT Filter 적용하여 인증기능 구현
- jwt filter를 거친 후 error 처리는 나중에 한번에 처리할 예정입니다. 현재는 jwt 인증이 되지 않으면 에러가 던저지면서 요청이 끝나게 하고 있습니다!
> feat: CORS 설정 & JWT Filter 구현

- meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
개발하면서 사용했던 클래스를 지우고 올렸는데, 의존성이 들어가있는걸 확인 못하고 푸시한걸 지금 확인해서 지우고 다시 올립니다..!
> fix: 존재하지 않는 클래스 의존성 제거 #22

- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/notice/application/NoticeService.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/entity/Notice.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/entity/NoticeType.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeRepository.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/vo/GetNoticesVO.java
- meongcare/src/main/java/com/meongcare/domain/notice/presentation/controller/NoticeController.java
- meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/request/PatchNoticeRequest.java
- meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/request/SaveNoticeRequest.java
- meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/response/GetNoticesResponse.java
- meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
> feat: 공지사항 API 구현

- meongcare/src/main/java/com/meongcare/MeongcareApplication.java
- meongcare/src/main/java/com/meongcare/common/DateTimePattern.java
- meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponse.java
- meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/Supplements.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsRecord.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsTime.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordJdbcRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsAndTimeVO.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineVO.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineWithoutStatusVO.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRateResponse.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsResponse.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRoutineResponse.java
- meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
- 영양제 API
- 알림은 목요일에 회의후 한번에 진행할 예정이라 제거하고 다시 올립니다!
> feat: 영양제 API

- .github/workflows/cicd-dev.yml
- meongcare/build.gradle
- meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequest.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsTime.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetAlarmSupplementsVO.java
- meongcare/src/main/java/com/meongcare/infra/config/FCMConfig.java
- meongcare/src/main/java/com/meongcare/infra/message/MessageHandler.java
- meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
- 영양제 알림 기능 구현
- 우선 구현은 완료됐는데, fcm token 발급 후 프론트랑 연결 해봐야할 것 같습니다. 테스트 서버에 배포하고 프론트 분과 같이 테스트 해볼 예정입니다.
- 그리고, @Scheduled 에서 cron을 사용해서 0초에 알림을 시작하려고 했었는데, 0초보다 일찍 시작하는 경우가 있어서 안전하게 cron= 2 * *~~ 으로 설정해서 적용했습니다.
> feat: 영양제 알림 기능 구현

- meongcare/.gitignore
- meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/PutDogRequest.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequest.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/response/GetDogResponse.java
> fix: 기획 수정사항 적용(강아지 등둘레 적용 및 날짜 리턴 타입 변경)

- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/response/GetDogsResponse.java
- 반려 동물 목록 조회 단건 조회 -> 리스트 조회로 수정
-
> fix: 반려동물 목록 조회 리스트 형식 수정

- meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomQueryRepository.java
soft delete를 하기 위한 execute 메서드가 생략되어 있던 부분을 수정했습니다.
> fix: execute 메서드 추가

- meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
- meongcare/src/main/java/com/meongcare/common/error/ErrorResponse.java
- meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
- meongcare/src/main/java/com/meongcare/common/error/exception/BaseException.java
- meongcare/src/main/java/com/meongcare/common/error/exception/EntityNotFoundException.java
- meongcare/src/main/java/com/meongcare/common/error/exception/FailedFileUploadException.java
- meongcare/src/main/java/com/meongcare/common/error/exception/InvalidTokenException.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtValidateArgumentResolver.java
- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
- meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRepository.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
- meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeRepository.java
- meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomRepository.java
- meongcare/src/main/java/com/meongcare/infra/image/s3/ImageHandlerS3.java
- 도메인 별 에러 처리 구현
~~Test 코드 작성~~
- 각 도메인별로 우선 ExceptionHandler 사용해서 예외처리 생각나는 부분 global하게 적용했습니다.
- test코드는 힘들것같아서,, 없이 작성했고 모든 도메인에서 id조회되는 부분은 공통으로 제가 처리했습니다.
- 패키지 구조나 공통 에러처리 부분 개선점 보이시면 말씀해주세요!
> feat: 도메인 별 예외 처리

- meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/response/GetSymptomForHomeResponse.java
메인 홈에서 ETC 타입인 이상증상인 경우 노트에 기록된 것을 활용하도록
Response DTO 수정
> fix: 이상증상 메인홈 Response DTO 수정

- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsInfoResponse.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsResponse.java
> feat: 강아지 ID 영양제 조회 기능 구현

- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
- meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
- meongcare/src/main/resources/application-local.yml
기본 생성자, 모든 필드 값 받는 생성자 만들어서 
잭슨 라이브러리가 역직렬화 할 수 있게 했습니다!
간단한거라 바로 머지할게요!!
> fix: 영양제 저장 요청값 역직렬화 안되는 문제 해결

- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
제 포스트맨으로는 되는데 소윤님은 415에러가 떠서 consumes 옵션 추가했습니다
> [FIX] 영양제 등록 요청 미디어 타입 설정

- meongcare/src/main/java/com/meongcare/common/error/exception/BaseException.java
- meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedDetailVO.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedRecordsVO.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedsVO.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedDetailResponse.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedRecordsResponse.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedsResponse.java
- 사료 상세 조회 API 구현, 사료 기록 조회 시 이미지 랜더링을 위해 이미지 링크 필드 추가,
사료 변경 시 null 처리되어야 하는 부분 로직 추가,
사료 조회 시 삭제 처리된 필드 조건 추가
- Resolved: #75 , #77
> feat: 사료 상세 조회 API 구현 및 사료 조회시 이미지 필드 추가, fix: 사료 변경 시 null 처리

- meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/dto/response/GetProfileResponse.java
- 내 장보 조회 repsonse에 알림 설정 여부 필드 추가
- Resolved: #79
> feat: 사용자 정보 조회 알림 설정 여부 필드 추가 (#79)

- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineVO.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineWithoutStatusVO.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsInfoResponse.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRoutineResponse.java
- 날짜 별 영양제 루틴 조회 api : 영양제 id도 반환
- 영양제 상세 조회 api : 이미지 링크, 활성화 여부도 반환
- Resolved: #81 
단순히 반환 값만 바꾼거라 merge 하겠습니다..!
> feat: supplementsId 응답 추가 (#81)

- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedRecordsVO.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedRecordsResponse.java
- 이전에 먹은 사료 조회 시 Response DTO에  feedId 필드 추가
- Resolved: #83
> feat: feedId 필드 추가

- .github/workflows/cicd-prod.yml
> yml 환경 설정 제거

- .github/workflows/cicd-prod.yml
> ECR_URI 설정

- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponse.java
- 최초 로그인 여부 추가했습니다~!
- Resolved: #92
> feat: 최초로그인 여부 추가 (#92)

- meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/Feed.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedDetailVO.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/EditFeedRequest.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/SaveFeedRequest.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedDetailResponse.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedResponse.java
- 사료 성분 100%가 안채워지면서 기타 필드로 나머지를 대체하기로 했습니다.
- Resolved: #91
> feat: 사료 성분 기타 필드 추가

- meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequest.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
- meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequest.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/Supplements.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
- meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
-  칼럼 제약 조건 설정
- validation 에러 핸들러 추가
- 로그인 시 provider id 에 @클랫폼 추가해서 db에 저장하도록 수정 (ex. `1111@google`)
회원 탈퇴는 크기가 커질 것 같아 나눠서 PR 하겠습니다
- Resolved: #94
> [FIX] 로그인 로직 수정, 검증 에러 응답 수정

- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
- meongcare/src/main/java/com/meongcare/infra/message/MessageHandler.java
- meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
- 전송하는 알림 메세지에서 로고 이미지는 제외
- 로그인 시 fcm 토큰 확인 후 새로 발급된 토큰이면 업데이트
- 알림 메세지 수정 
- Resolved: #108
> 알림 메세지 수정, 로그인 시 fcm 확인 #108

- meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/Feed.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/FeedRecord.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
- meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/SaveFeedRequest.java
- 테이블 설계가 잘못되었다고 판단해서 전체 로직 수정했습니다.
- Resolved: #109
> 사료 활성화 로직 수정

- meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
> 사료 기록 삭제 쿼리 수정

- meongcare/src/main/java/com/meongcare/common/BaseEntity.java
- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
- meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
- meongcare/src/main/java/com/meongcare/domain/notice/application/NoticeService.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
> [REFACTOR] 메서드 이름 변경 #114

- meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
- meongcare/src/main/java/com/meongcare/common/error/ErrorResponse.java
- meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
- meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
- 파라미터 누락 관련 에러 400으로 처리했습니다!
- Resolved: #123
> [FEAT] 잘못된 파라미터 요청 처리 #123

- meongcare/src/main/java/com/meongcare/common/event/EventListener.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/dto/FcmNotificationDTO.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationRecord.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationType.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/repository/NotificationRecordRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
- meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetAlarmSupplementsVO.java
- meongcare/src/main/java/com/meongcare/infra/message/MessageHandler.java
- meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
- 알림 이벤트 발행 및 비동기 처리, 알림 전송 실패 시 DB에 저장(활용 방법은 추가 고민 필요)
- Resolved: #125, #126
> 알림 이벤트 발행 및 비동기 처리, 알림 전송 실패 시 DB에 저장

- meongcare/src/main/resources/logback-spring.xml
> [FIX]운영 서버 로그 모니터링 설정 변경 #134

- meongcare/src/main/java/com/meongcare/domain/notifciation/application/NotificationScheduler.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/application/NotificationService.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationRecord.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/repository/NotificationRecordQueryRepository.java
- meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
- 알림 실패 시 재시도하는 스케줄러와 로직을 추가했습니다.
- Resolved: #137
> 알림 실패 시 재시도하는 스케줄러 및 기능 추가

- meongcare/src/main/resources/logback-spring.xml
- yml dev, prod 둘 다 변경 있습니다! 노션에 올려둘게요 secret actions는 변경했습니다
- Resolved: #140
> feat: logback-spring.xml 프로필 설정 변경

- meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
- meongcare/src/main/resources/logback-spring.xml
- 알림 에러 발생 시 로그 레벨 error로 변경했습니다!
> 알림 로그 레벨 변경

- meongcare/build.gradle
- meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/excreta/application/ExcretaService.java
- meongcare/src/main/java/com/meongcare/domain/symptom/application/SymptomService.java
- meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
- meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetMonthWeightResponse.java
- meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeekWeightResponse.java
- meongcare/src/test/java/com/meongcare/domain/weight/application/WeightServiceTest.java
> WeightService 테스트 코드 작성

- meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
- meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
- meongcare/src/main/java/com/meongcare/domain/notifciation/domain/dto/FcmNotificationDTO.java
> refactor: member로 이름 변경

- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordQueryRepository.java
- 진료기록이 아니라 사료기록을 변경하고 있었네요,,,
- Resolved: #155
> fix: feedRecord->medicalRecord (#155)

- meongcare/src/main/java/com/meongcare/domain/file/s3/application/PreSignedUrlService.java
- meongcare/src/main/java/com/meongcare/domain/file/s3/presentation/AwsS3Controller.java
- meongcare/src/main/java/com/meongcare/domain/file/s3/presentation/dto/response/PreSignedUrlResponse.java
- 백엔드에서 업로드하지 않고 클라이언트에서 업로드하기 위해 presigned URL을 사용하고자 합니다.
일단 안드로이드가 사용할 수 있을 정도로 구현해두고 추가로 디벨롭 하겠습니다~
- Resolved: #152
> feat: preSignedUrl 생성 로직 구현

- meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/dto/request/EditProfileImageRequest.java
- 프로필 수정 API도  presignedURL을 적용했습니다.
- Resolved: #164
> 프로필 수정 API presignedURL 적용

- meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
- meongcare/src/main/java/com/meongcare/domain/member/presentation/dto/request/EditProfileImageRequest.java
- memberId를 상태관리 안하고 있어서 토큰에서 찾는 걸로 변경했습니다
- Resolved: #166
> 프로필 수정 API 수정

- meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/entity/MedicalRecord.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequest.java
- meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequest.java
- 안드로이드 진료기록 CRUD 적용이 끝나서 해당 부분 presignedURL로 개선할 수 있도록 API 수정했습니다~
- Resolved: #168
> medicalRecord preSignedURL 적용

- meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
- meongcare/src/main/java/com/meongcare/domain/dog/domain/repository/MemberDogQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberQueryRepository.java
- meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
> fix: 쿼리 결과에서 가져온 연관 관계의 소유자 선택

- meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
> docs: api 문서 수정
